version: "3.5"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
    command: ["npm", "run", "watch"]
    healthcheck:
      test: curl -f http://api
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 120s
    depends_on:
      - mysql
    networks:
      - overlay

  mysql:
    image: mysql:8
    ports:
      - "${DB_EXTERNAL_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./.docker-storage/db/auth:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    healthcheck:
      test: mysqladmin -u${DB_USER:-root} -p${DB_PASS:-password1} ping
      interval: 5s
      timeout: 10s
      retries: 30
    networks:
      - overlay

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${DB_ADMIN_PORT}:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    healthcheck:
      test: curl -f http://phpmyadmin
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 120s
    depends_on:
      - mysql
    networks:
      - overlay

networks:
  overlay:
